In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model


SyntaxError: invalid syntax (<ipython-input-3-483da7519d92>, line 4)

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv')

In [5]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [10]:
df.experience = df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [12]:
#Preprocessing
import math
test_med = math.floor(df['test_score(out of 10)'].median())
test_med

8

In [14]:
df.experience = df.replace({'zero':0,'five':5,'two':2,'seven':7,'three':3,'ten':10,'eleven':11})
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [15]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(test_med)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [18]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [19]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [20]:
reg.intercept_

17737.26346433771

In [22]:
reg.predict([[2.0,9,6]])

array([53205.96797671])

In [23]:
reg.predict([[12.0,10,10]])

array([92002.18340611])